name: ci

on: [push, pull_request]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
    name: Running on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.17.0"

      - name: Install yarn
        run: npm i yarn -g 

      - name: Install dependencies
        run: yarn install

      - name: Run formatter
        run: yarn format

      - name: Run linter
        run: yarn lint
