name: Ci

on: [push, pull_request]

jobs:
  build:
    runs-on: Build on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        node_version:
          - 14.17.0
        architecture:
          - x64
    name: Node ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}

      - name: Setup yarn
        run: npm i yarn -g

      - name: Format
        run: yarn run format:check

      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build
